modLoader="javafml"
loaderVersion="[47,)"
license="Creative Commons Attribution-ShareAlike 4.0"

[[mods]]
modId="luna_nights"
version="1.0.0"
displayName="Touhou Luna Nights"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Bl4ues"

[[dependencies.luna_nights]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




